DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'culinary') THEN
        CREATE SCHEMA culinary;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS culinary."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'culinary') THEN
            CREATE SCHEMA culinary;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetUsers" (
        "Id" character varying(450) NOT NULL,
        "DisplayName" character varying(100) NOT NULL,
        "AvatarUrl" character varying(500),
        "Bio" text,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."Categories" (
        "Id" uuid NOT NULL,
        "Name" character varying(100) NOT NULL,
        "Slug" character varying(120) NOT NULL,
        "Description" text,
        "ImageUrl" character varying(500),
        "OrderIndex" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Categories_Name" CHECK (length(btrim("Name")) > 0),
        CONSTRAINT "CK_Categories_Order" CHECK ("OrderIndex" >= 0),
        CONSTRAINT "CK_Categories_RowVersion" CHECK (octet_length("RowVersion") = 16),
        CONSTRAINT "CK_Categories_Slug" CHECK (length(btrim("Slug")) > 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES culinary."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" character varying(450) NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetUserRoles" (
        "UserId" character varying(450) NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES culinary."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."AspNetUserTokens" (
        "UserId" character varying(450) NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."RefreshTokens" (
        "Id" uuid NOT NULL,
        "UserId" character varying(450) NOT NULL,
        "TokenHash" character varying(64) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ExpiresAt" timestamp with time zone NOT NULL,
        "RevokedAt" timestamp with time zone,
        "ReplacedByTokenHash" character varying(64),
        "CreatedByIp" character varying(45),
        CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RefreshTokens_Expiry" CHECK ("ExpiresAt" > "CreatedAt"),
        CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."Recipes" (
        "Id" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Slug" character varying(220) NOT NULL,
        "Description" text NOT NULL,
        "Instructions" text NOT NULL DEFAULT '',
        "PrepTime" integer NOT NULL,
        "CookTime" integer NOT NULL,
        "Servings" integer NOT NULL,
        "Difficulty" smallint NOT NULL,
        "Status" smallint NOT NULL,
        "PublishedAt" timestamp with time zone,
        "CategoryId" uuid NOT NULL,
        "AuthorId" character varying(450) NOT NULL,
        "Nutrition_Calories" numeric(8,2),
        "Nutrition_Protein" numeric(8,2),
        "Nutrition_Carbohydrates" numeric(8,2),
        "Nutrition_Fat" numeric(8,2),
        "Nutrition_Fiber" numeric(8,2),
        "Nutrition_Sodium" numeric(8,2),
        "SearchVector" tsvector,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_Recipes" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Recipes_Description" CHECK (length(btrim("Description")) BETWEEN 1 AND 2000),
        CONSTRAINT "CK_Recipes_Enums" CHECK ("Status" BETWEEN 0 AND 2 AND "Difficulty" BETWEEN 1 AND 4),
        CONSTRAINT "CK_Recipes_Nutrition_Calories" CHECK ("Nutrition_Calories" IS NULL OR "Nutrition_Calories" >= 0),
        CONSTRAINT "CK_Recipes_Nutrition_Carbohydrates" CHECK ("Nutrition_Carbohydrates" IS NULL OR "Nutrition_Carbohydrates" >= 0),
        CONSTRAINT "CK_Recipes_Nutrition_Fat" CHECK ("Nutrition_Fat" IS NULL OR "Nutrition_Fat" >= 0),
        CONSTRAINT "CK_Recipes_Nutrition_Fiber" CHECK ("Nutrition_Fiber" IS NULL OR "Nutrition_Fiber" >= 0),
        CONSTRAINT "CK_Recipes_Nutrition_Protein" CHECK ("Nutrition_Protein" IS NULL OR "Nutrition_Protein" >= 0),
        CONSTRAINT "CK_Recipes_Nutrition_Sodium" CHECK ("Nutrition_Sodium" IS NULL OR "Nutrition_Sodium" >= 0),
        CONSTRAINT "CK_Recipes_PublishedAt" CHECK ("Status" <> 1 OR "PublishedAt" IS NOT NULL),
        CONSTRAINT "CK_Recipes_RowVersion" CHECK (octet_length("RowVersion") = 16),
        CONSTRAINT "CK_Recipes_Slug" CHECK (length(btrim("Slug")) > 0),
        CONSTRAINT "CK_Recipes_Times" CHECK ("PrepTime" > 0 AND "CookTime" >= 0 AND "Servings" > 0),
        CONSTRAINT "CK_Recipes_Title" CHECK (length(btrim("Title")) BETWEEN 5 AND 200),
        CONSTRAINT "FK_Recipes_AspNetUsers_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES culinary."AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Recipes_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES culinary."Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."RecipeImages" (
        "Id" uuid NOT NULL,
        "RecipeId" uuid NOT NULL,
        "OriginalUrl" character varying(500) NOT NULL,
        "MediumUrl" character varying(500),
        "ThumbnailUrl" character varying(500),
        "AltText" character varying(200),
        "IsPrimary" boolean NOT NULL,
        "OrderIndex" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_RecipeImages" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Images_Order" CHECK ("OrderIndex" >= 0),
        CONSTRAINT "CK_Images_Original" CHECK (length(btrim("OriginalUrl")) > 0),
        CONSTRAINT "CK_RecipeImages_RowVersion" CHECK (octet_length("RowVersion") = 16),
        CONSTRAINT "FK_RecipeImages_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES culinary."Recipes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."RecipeIngredients" (
        "Id" uuid NOT NULL,
        "RecipeId" uuid NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Quantity" numeric(10,3),
        "Unit" character varying(50),
        "Notes" character varying(500),
        "OrderIndex" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_RecipeIngredients" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Ingredients_Name" CHECK (length(btrim("Name")) BETWEEN 1 AND 200),
        CONSTRAINT "CK_Ingredients_Order" CHECK ("OrderIndex" >= 0),
        CONSTRAINT "CK_Ingredients_QuantityUnit" CHECK (("Quantity" IS NULL AND "Unit" IS NULL) OR ("Quantity" IS NOT NULL AND "Quantity" > 0 AND "Unit" IS NOT NULL AND length(btrim("Unit")) > 0)),
        CONSTRAINT "CK_RecipeIngredients_RowVersion" CHECK (octet_length("RowVersion") = 16),
        CONSTRAINT "FK_RecipeIngredients_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES culinary."Recipes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE TABLE culinary."RecipeSteps" (
        "Id" uuid NOT NULL,
        "RecipeId" uuid NOT NULL,
        "StepNumber" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text NOT NULL,
        "TimerMinutes" integer,
        "ImageUrl" character varying(500),
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "RowVersion" bytea NOT NULL,
        CONSTRAINT "PK_RecipeSteps" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_RecipeSteps_RowVersion" CHECK (octet_length("RowVersion") = 16),
        CONSTRAINT "CK_Steps_Description" CHECK (length(btrim("Description")) BETWEEN 1 AND 2000),
        CONSTRAINT "CK_Steps_Number" CHECK ("StepNumber" > 0),
        CONSTRAINT "CK_Steps_Timer" CHECK ("TimerMinutes" IS NULL OR "TimerMinutes" >= 0),
        CONSTRAINT "CK_Steps_Title" CHECK (length(btrim("Title")) > 0),
        CONSTRAINT "FK_RecipeSteps_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES culinary."Recipes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON culinary."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON culinary."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON culinary."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON culinary."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON culinary."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "EmailIndex" ON culinary."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON culinary."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "IX_Categories_Slug" ON culinary."Categories" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "IX_RecipeImages_RecipeId" ON culinary."RecipeImages" ("RecipeId") WHERE "IsPrimary" AND NOT "IsDeleted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_RecipeImages_RecipeId_OrderIndex_Id" ON culinary."RecipeImages" ("RecipeId", "OrderIndex", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_RecipeIngredients_RecipeId_OrderIndex_Id" ON culinary."RecipeIngredients" ("RecipeId", "OrderIndex", "Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_Recipes_AuthorId_Status_CreatedAt_Id" ON culinary."Recipes" ("AuthorId", "Status", "CreatedAt", "Id") WHERE NOT "IsDeleted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_Recipes_CategoryId" ON culinary."Recipes" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_Recipes_CreatedAt_Id" ON culinary."Recipes" ("CreatedAt" DESC, "Id" DESC) WHERE NOT "IsDeleted" AND "Status" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_Recipes_SearchVector" ON culinary."Recipes" USING GIN ("SearchVector");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "IX_Recipes_Slug" ON culinary."Recipes" ("Slug");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_RecipeSteps_RecipeId" ON culinary."RecipeSteps" ("RecipeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "IX_RecipeSteps_RecipeId_StepNumber" ON culinary."RecipeSteps" ("RecipeId", "StepNumber") WHERE NOT "IsDeleted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_RefreshTokens_ExpiresAt" ON culinary."RefreshTokens" ("ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE UNIQUE INDEX "IX_RefreshTokens_TokenHash" ON culinary."RefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    CREATE INDEX "IX_RefreshTokens_UserId" ON culinary."RefreshTokens" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921055928_InitialLab2RecipeSchema') THEN
    INSERT INTO culinary."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921055928_InitialLab2RecipeSchema', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921060000_AddRecipeSearchSupport') THEN
    CREATE SCHEMA IF NOT EXISTS extensions;
    CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA extensions;
    CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA extensions;
    CREATE TEXT SEARCH CONFIGURATION culinary.vietnamese (COPY = pg_catalog.simple);
    DO $block$
    DECLARE extension_schema text;
    BEGIN
        SELECT n.nspname INTO extension_schema
        FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
        WHERE e.extname='unaccent';
        EXECUTE format('ALTER TEXT SEARCH CONFIGURATION culinary.vietnamese ALTER MAPPING FOR hword, hword_part, word WITH %I.unaccent, pg_catalog.simple', extension_schema);
    END $block$;
    CREATE FUNCTION culinary.update_recipe_search() RETURNS trigger
    LANGUAGE plpgsql AS $body$
    BEGIN
        NEW."SearchVector" := setweight(to_tsvector('culinary.vietnamese', coalesce(NEW."Title",'')), 'A')
            || setweight(to_tsvector('culinary.vietnamese', coalesce(NEW."Description",'')), 'B');
        RETURN NEW;
    END $body$;
    CREATE TRIGGER recipe_search BEFORE INSERT OR UPDATE OF "Title", "Description"
        ON culinary."Recipes" FOR EACH ROW EXECUTE FUNCTION culinary.update_recipe_search();
    UPDATE culinary."Recipes" SET "Title"="Title";
    CREATE UNIQUE INDEX "IX_Categories_Name_CaseInsensitive" ON culinary."Categories" (lower("Name"));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM culinary."__EFMigrationsHistory" WHERE "MigrationId" = '20260921060000_AddRecipeSearchSupport') THEN
    INSERT INTO culinary."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260921060000_AddRecipeSearchSupport', '10.0.12');
    END IF;
END $EF$;
COMMIT;

