import { Category, Recipe, User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "usr-1",
    displayName: "Bếp Trưởng Hoàng Linh",
    userName: "hoanglinh_chef",
    email: "hoanglinh@culinaryblog.vn",
    avatarUrl: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=200&auto=format&fit=crop&q=80",
    bio: "Đầu bếp ẩm thực truyền thống Việt Nam với hơn 10 năm kinh nghiệm gìn giữ và sáng tạo hương vị Việt.",
    role: "User",
    createdAt: "2024-01-15T08:00:00Z",
  },
  {
    id: "usr-2",
    displayName: "Mai Phương Thảo",
    userName: "thaomai_bakes",
    email: "thaomai@culinaryblog.vn",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    bio: "Tín đồ làm bánh ngọt và món tráng miệng gia đình. Yêu căn bếp ấm cúng và tách trà thảo mộc mỗi chiều.",
    role: "User",
    createdAt: "2024-03-20T09:30:00Z",
  },
  {
    id: "usr-3",
    displayName: "Trần Minh Quân",
    userName: "quan_kitchen",
    email: "minhquan@culinaryblog.vn",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    bio: "Chàng trai mê nấu nướng cuối tuần, đặc biệt yêu thích các món đường phố và đặc sản 3 miền.",
    role: "User",
    createdAt: "2024-02-10T14:15:00Z",
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-all",
    name: "Tất cả",
    slug: "all",
    description: "Khám phá toàn bộ kho tàng công thức ẩm thực độc đáo",
    icon: "Utensils",
    recipeCount: 24,
  },
  {
    id: "cat-1",
    name: "Món sáng",
    slug: "mon-sang",
    description: "Khởi đầu ngày mới tràn đầy năng lượng với các món ăn sáng thanh nhẹ, bổ dưỡng",
    icon: "Sunrise",
    recipeCount: 6,
  },
  {
    id: "cat-2",
    name: "Món trưa",
    slug: "mon-trua",
    description: "Bữa trưa đậm đà, nhanh gọn nhưng đủ chất cho gia đình và giới văn phòng",
    icon: "Sun",
    recipeCount: 8,
  },
  {
    id: "cat-3",
    name: "Món tối",
    slug: "mon-toi",
    description: "Mâm cơm tối ấm cúng gắn kết gia đình sau một ngày làm việc tất bật",
    icon: "Moon",
    recipeCount: 7,
  },
  {
    id: "cat-4",
    name: "Tráng miệng",
    slug: "trang-mieng",
    description: "Những món ngọt ngào, mát lạnh làm dịu tan mọi mỏi mệt",
    icon: "Cake",
    recipeCount: 5,
  },
  {
    id: "cat-5",
    name: "Đồ uống",
    slug: "do-uong",
    description: "Thức uống thanh mát, sinh tố và trà trái cây thanh lọc cơ thể",
    icon: "Coffee",
    recipeCount: 4,
  },
  {
    id: "cat-6",
    name: "Ăn vặt",
    slug: "an-vat",
    description: "Các món quà vặt đường phố giòn rụm, cay nồng dễ gây nghiện",
    icon: "Cookie",
    recipeCount: 5,
  },
];

export const INITIAL_RECIPES: Recipe[] = [
  {
    id: "rcp-1",
    title: "Phở Bò Tái Lăn Hà Nội Gia Truyền",
    slug: "pho-bo-tai-lan-ha-noi",
    description: "Bí quyết nấu nước dùng phở bò trong veo, thơm nức mùi gừng nướng, hoa hồi và thảo quả, kết hợp thịt bò xào lăn lửa lớn béo ngậy.",
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficultyLevel: "Hard",
    status: "Published",
    images: [
      {
        id: "img-1-1",
        url: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Bát phở bò tái lăn bốc khói nghi ngút",
      },
      {
        id: "img-1-2",
        url: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=1200&auto=format&fit=crop&q=80",
        isPrimary: false,
        caption: "Gia vị thảo mộc ninh nước dùng",
      },
    ],
    ingredients: [
      { id: "ing-1", amount: "1", unit: "kg", name: "Xương ống bò tươi" },
      { id: "ing-2", amount: "500", unit: "g", name: "Thịt thăn bò mềm" },
      { id: "ing-3", amount: "500", unit: "g", name: "Bánh phở tươi sợi nhỏ" },
      { id: "ing-4", amount: "2", unit: "củ", name: "Hành tây trắng" },
      { id: "ing-5", amount: "1", unit: "nhánh", name: "Gừng tươi nướng thơm" },
      { id: "ing-6", amount: "3", unit: "hoa", name: "Hoa hồi, quế chi, thảo quả" },
      { id: "ing-7", amount: "1", unit: "bó", name: "Hành hoa và ngò gai tươi" },
      { id: "ing-8", amount: "2", unit: "muỗng canh", name: "Nước mắm cốt truyền thống" },
    ],
    steps: [
      {
        id: "stp-1",
        stepNumber: 1,
        description: "Xương ống bò ngâm nước muối 1 giờ, chần nước sôi cùng gừng đập dập để khử sạch mùi hôi. Rửa sạch lại bằng nước ấm.",
        imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "stp-2",
        stepNumber: 2,
        description: "Nướng hoa hồi, quế, thảo quả, hành tây và gừng trên than hoa hoặc chảo gang cho cháy xém vỏ, dậy mùi thơm nức.",
      },
      {
        id: "stp-3",
        stepNumber: 3,
        description: "Cho xương và gói gia vị nướng vào nồi 4 lít nước. Ninh nhỏ lửa liu riu trong 3 giờ, hớt bọt thường xuyên để nước trong vắt.",
        imageUrl: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "stp-4",
        stepNumber: 4,
        description: "Thái mỏng thịt thăn bò. Đun nóng chảo gang với mỡ tỏi, trút thịt bò vào xào lăn lửa lớn trong 40 giây cho chín tới rồi tắt bếp.",
      },
      {
        id: "stp-5",
        stepNumber: 5,
        description: "Chần bánh phở, xếp vào bát, đặt thịt bò xào lăn lên trên cùng đầu hành chẻ và ngò gai. Chan nước dùng sôi sùng sục và thưởng thức.",
      },
    ],
    nutrition: {
      calories: 520,
      protein: 38,
      carbs: 65,
      fat: 14,
    },
    author: MOCK_USERS[0],
    category: MOCK_CATEGORIES[1], // Món sáng
    createdAt: "2024-05-10T07:30:00Z",
    updatedAt: "2024-05-12T10:00:00Z",
    viewsCount: 3840,
    likesCount: 342,
  },
  {
    id: "rcp-2",
    title: "Cá Hồi Áp Chảo Sốt Bơ Chanh Măng Tây",
    slug: "ca-hoi-ap-chao-sot-bo-chanh",
    description: "Miếng phi lê cá hồi da giòn rụm bên ngoài, thịt mọng nước hồng hào bên trong, hòa quyện sốt bơ chanh vàng óng chua dịu.",
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficultyLevel: "Medium",
    status: "Published",
    images: [
      {
        id: "img-2-1",
        url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Đĩa cá hồi áp chảo sốt bơ chanh cao cấp",
      },
      {
        id: "img-2-2",
        url: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=1200&auto=format&fit=crop&q=80",
        isPrimary: false,
        caption: "Áp chảo cá hồi trên chảo chống dính",
      },
    ],
    ingredients: [
      { id: "ing-2-1", amount: "400", unit: "g", name: "Phi lê cá hồi tươi còn da" },
      { id: "ing-2-2", amount: "40", unit: "g", name: "Bơ lạt Pháp cao cấp" },
      { id: "ing-2-3", amount: "1", unit: "quả", name: "Chanh vàng lấy nước cốt và vỏ bào" },
      { id: "ing-2-4", amount: "200", unit: "g", name: "Măng tây xanh non" },
      { id: "ing-2-5", amount: "2", unit: "nhánh", name: "Xạ hương (thyme) và tỏi đập dập" },
      { id: "ing-2-6", amount: "1/2", unit: "muỗng cà phê", name: "Muối hồng biển và tiêu đen xay" },
    ],
    steps: [
      {
        id: "stp-2-1",
        stepNumber: 1,
        description: "Dùng khăn giấy thấm thật khô miếng cá hồi. Rắc đều muối hồng và tiêu đen lên cả hai mặt. Khía nhẹ 2 đường trên lớp da.",
      },
      {
        id: "stp-2-2",
        stepNumber: 2,
        description: "Làm nóng chảo với 1 muỗng dầu olive. Đặt mặt da cá xuống áp chảo ở lửa vừa trong 4-5 phút đến khi da vàng giòn tan.",
        imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "stp-2-3",
        stepNumber: 3,
        description: "Lật mặt cá, thêm bơ, tỏi và nhánh thyme vào chảo. Dùng thìa rưới liên tục bơ nóng lên thịt cá trong 2 phút rồi gắp ra đĩa nghỉ.",
      },
      {
        id: "stp-2-4",
        stepNumber: 4,
        description: "Tận dụng chảo đảo nhanh măng tây chín tới. Hòa nước cốt chanh vào bơ còn lại tạo thành sốt sánh mịn rồi rưới lên cá.",
      },
    ],
    nutrition: {
      calories: 460,
      protein: 42,
      carbs: 8,
      fat: 28,
    },
    author: MOCK_USERS[0],
    category: MOCK_CATEGORIES[3], // Món tối
    createdAt: "2024-05-15T18:00:00Z",
    updatedAt: "2024-05-15T18:00:00Z",
    viewsCount: 2910,
    likesCount: 275,
  },
  {
    id: "rcp-3",
    title: "Bún Chả Hà Nội Nướng Than Hoa",
    slug: "bun-cha-ha-noi-nuong-than-hoa",
    description: "Chả miếng ba chỉ béo ngậy cùng chả viên thơm thảo mộc nướng xém cạnh trên than hoa, chấm ngập trong chén nước mắm chua ngọt ấm nồng đu đủ giòn.",
    prepTime: 45,
    cookTime: 30,
    servings: 4,
    difficultyLevel: "Medium",
    status: "Published",
    images: [
      {
        id: "img-3-1",
        url: "https://images.unsplash.com/photo-1503764654157-72d979d9af2f?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Bàn bún chả thơm lừng ngập tràn rau sống",
      },
    ],
    ingredients: [
      { id: "ing-3-1", amount: "500", unit: "g", name: "Thịt ba chỉ thái mỏng" },
      { id: "ing-3-2", amount: "500", unit: "g", name: "Thịt nạc vai xay nhuyễn" },
      { id: "ing-3-3", amount: "1", unit: "kg", name: "Bún tươi sợi con" },
      { id: "ing-3-4", amount: "1/2", unit: "quả", name: "Đu đủ xanh và cà rốt làm dưa góp" },
      { id: "ing-3-5", amount: "3", unit: "muỗng canh", name: "Nước hàng (caramel) tự thắng" },
      { id: "ing-3-6", amount: "1", unit: "rổ", name: "Rau sống: xà lách, tía tô, kinh giới" },
    ],
    steps: [
      {
        id: "stp-3-1",
        stepNumber: 1,
        description: "Ướp thịt ba chỉ và thịt xay riêng biệt với hành khô băm, nước mắm ngon, dầu hào, tiêu và nước hàng trong 2 tiếng.",
      },
      {
        id: "stp-3-2",
        stepNumber: 2,
        description: "Vo tròn thịt xay thành viên dẹt. Kẹp chả miếng và chả viên vào vỉ nướng trên than hoa đượm lửa, lật đều tay đến khi vàng óng.",
      },
      {
        id: "stp-3-3",
        stepNumber: 3,
        description: "Pha nước chấm theo tỷ lệ vàng 1 mắm : 1 đường : 1 giấm : 5 nước ấm, thêm tỏi ớt băm nhỏ và dưa góp giòn sần sật.",
      },
    ],
    nutrition: {
      calories: 610,
      protein: 34,
      carbs: 72,
      fat: 22,
    },
    author: MOCK_USERS[2],
    category: MOCK_CATEGORIES[2], // Món trưa
    createdAt: "2024-04-22T11:00:00Z",
    updatedAt: "2024-04-22T11:00:00Z",
    viewsCount: 4120,
    likesCount: 390,
  },
  {
    id: "rcp-4",
    title: "Chè Khúc Bạch Hạnh Nhân Thanh Mát",
    slug: "che-khuc-bach-hanh-nhan",
    description: "Món tráng miệng thanh mát giải nhiệt mùa hè với từng viên khúc bạch sữa tươi béo ngậy, long nhãn mọng nước và hạnh nhân rang giòn.",
    prepTime: 25,
    cookTime: 20,
    servings: 4,
    difficultyLevel: "Easy",
    status: "Published",
    images: [
      {
        id: "img-4-1",
        url: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Bát chè khúc bạch trong veo giải nhiệt",
      },
    ],
    ingredients: [
      { id: "ing-4-1", amount: "250", unit: "ml", name: "Sữa tươi không đường" },
      { id: "ing-4-2", amount: "250", unit: "ml", name: "Whipping cream nguyên chất" },
      { id: "ing-4-3", amount: "25", unit: "g", name: "Gelatin bột ngâm nở" },
      { id: "ing-4-4", amount: "100", unit: "g", name: "Đường phèn kết tinh" },
      { id: "ing-4-5", amount: "1", unit: "hộp", name: "Vải hoặc nhãn ngâm đường phèn" },
      { id: "ing-4-6", amount: "50", unit: "g", name: "Hạnh nhân lát rang thơm vàng" },
    ],
    steps: [
      {
        id: "stp-4-1",
        stepNumber: 1,
        description: "Đun cách thủy sữa tươi, kem tươi và đường cho ấm (khoảng 60 độ C). Trút gelatin đã ngâm nở vào khuấy tan hoàn toàn.",
      },
      {
        id: "stp-4-2",
        stepNumber: 2,
        description: "Đổ hỗn hợp qua rây vào khuôn, cất ngăn mát tủ lạnh ít nhất 4 tiếng đến khi thạch đông dẻo mịn. Dùng dao lượn sóng cắt miếng vuông.",
      },
      {
        id: "stp-4-3",
        stepNumber: 3,
        description: "Nấu nước đường phèn thanh nhẹ cùng lá dứa, để thật nguội. Cho khúc bạch, nhãn ngâm, đá viên và rắc hạnh nhân lên trên.",
      },
    ],
    nutrition: {
      calories: 320,
      protein: 7,
      carbs: 45,
      fat: 14,
    },
    author: MOCK_USERS[1],
    category: MOCK_CATEGORIES[4], // Tráng miệng
    createdAt: "2024-05-02T15:30:00Z",
    updatedAt: "2024-05-02T15:30:00Z",
    viewsCount: 1980,
    likesCount: 184,
  },
  {
    id: "rcp-5",
    title: "Cơm Tấm Sườn Bì Chả Trứng Ốp La",
    slug: "com-tam-suon-bi-cha-sai-gon",
    description: "Đặc sản Sài Gòn nức tiếng với sườn nướng mật ong óng ả, chả trứng hấp bùi bùi, bì heo dai giòn thơm thính và mỡ hành thơm ngát.",
    prepTime: 30,
    cookTime: 40,
    servings: 4,
    difficultyLevel: "Medium",
    status: "Published",
    images: [
      {
        id: "img-5-1",
        url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Dĩa cơm tấm sườn bì chả đầy ắp",
      },
    ],
    ingredients: [
      { id: "ing-5-1", amount: "4", unit: "miếng", name: "Sườn cốt lết dày dặn" },
      { id: "ing-5-2", amount: "400", unit: "g", name: "Gạo tấm thơm dẻo" },
      { id: "ing-5-3", amount: "200", unit: "g", name: "Bì heo trộn thính gạo thơm" },
      { id: "ing-5-4", amount: "4", unit: "quả", name: "Trứng gà ta (chiên ốp la lòng đào)" },
      { id: "ing-5-5", amount: "1", unit: "chén", name: "Mỡ hành và tóp mỡ giòn" },
      { id: "ing-5-6", amount: "1", unit: "chén", name: "Nước mắm chua ngọt kẹo quánh" },
    ],
    steps: [
      {
        id: "stp-5-1",
        stepNumber: 1,
        description: "Dần mềm miếng sườn rồi ướp cùng mật ong, sữa đặc, tỏi sả băm, nước tương và dầu hào trong 3 tiếng.",
      },
      {
        id: "stp-5-2",
        stepNumber: 2,
        description: "Nướng sườn trên lửa vừa, quét hỗn hợp ướp liên tục cho mặt thịt bóng bẩy và thơm phức.",
      },
      {
        id: "stp-5-3",
        stepNumber: 3,
        description: "Xới cơm tấm nóng ra dĩa, đặt sườn, chả trứng, bì heo, ốp la và rưới đẫm mỡ hành óng ả.",
      },
    ],
    nutrition: {
      calories: 680,
      protein: 45,
      carbs: 80,
      fat: 24,
    },
    author: MOCK_USERS[2],
    category: MOCK_CATEGORIES[2], // Món trưa
    createdAt: "2024-05-18T10:00:00Z",
    updatedAt: "2024-05-18T10:00:00Z",
    viewsCount: 5240,
    likesCount: 489,
  },
  {
    id: "rcp-6",
    title: "Trà Đào Cam Sả Mật Ong Rừng",
    slug: "tra-dao-cam-sa-mat-ong",
    description: "Thức uống giải khát quốc dân với hương thơm nồng nàn từ sả tươi, vị chua thanh của cam vàng và miếng đào ngâm giòn ngọt mọng nước.",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficultyLevel: "Easy",
    status: "Published",
    images: [
      {
        id: "img-6-1",
        url: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=1200&auto=format&fit=crop&q=80",
        isPrimary: true,
        caption: "Ly trà đào cam sả mát lạnh",
      },
    ],
    ingredients: [
      { id: "ing-6-1", amount: "2", unit: "gói", name: "Trà túi lọc Earl Grey hoặc Cozy đào" },
      { id: "ing-6-2", amount: "3", unit: "cây", name: "Sả tươi đập dập" },
      { id: "ing-6-3", amount: "1", unit: "quả", name: "Cam vàng Mỹ mọng nước" },
      { id: "ing-6-4", amount: "3", unit: "muỗng canh", name: "Mật ong hoa rừng nguyên chất" },
      { id: "ing-6-5", amount: "4", unit: "miếng", name: "Đào ngâm giòn đóng hộp" },
    ],
    steps: [
      {
        id: "stp-6-1",
        stepNumber: 1,
        description: "Đun sôi 400ml nước cùng sả đập dập trong 5 phút để chiết xuất trọn vẹn tinh dầu thơm.",
      },
      {
        id: "stp-6-2",
        stepNumber: 2,
        description: "Thả gói trà vào hãm 5 phút rồi vớt túi lọc ra, để nước trà nguội bớt.",
      },
      {
        id: "stp-6-3",
        stepNumber: 3,
        description: "Vắt nước cam, hòa cùng mật ong và nước cốt đào ngâm. Cho đá viên đầy ly, rót trà sả và trang trí miếng đào tươi.",
      },
    ],
    nutrition: {
      calories: 140,
      protein: 1,
      carbs: 34,
      fat: 0,
    },
    author: MOCK_USERS[1],
    category: MOCK_CATEGORIES[5], // Đồ uống
    createdAt: "2024-05-20T14:00:00Z",
    updatedAt: "2024-05-20T14:00:00Z",
    viewsCount: 1650,
    likesCount: 152,
  },
];
